---
title: Polymer in Angular-CLI Apps
order: 3
layout: page
---

[[vaadin-angular2-polymer.ng2cli]]
= Using Polymer Elements with Angular-CLI Apps

[[vaadin-angular2-polymer.ng2cli.introduction]]
== Introduction

https://github.com/angular/angular-cli[Angular-CLI] is a command line tool for Angular 2. It is not only a scaffolding tool for creating and modifying a project, but also for other actions like building, running, debugging, and testing the project.

In this document we will describe all the modifications you have to make to your Angular-CLI project to use Polymer elements.


[[vaadin-angular2-polymer.ng2cli.preparation]]
== Preparation

Install the Angular-CLI in your system, and create a new Angular 2 project.

[subs="normal"]
----
[prompt]#$# [command]#npm# install angular-cli -g
[prompt]#$# [command]#ng# new [replaceable]#my-project#
----

Check that everything works by compiling, testing, and running your project:

[subs="normal"]
----
[prompt]#$# [command]#cd# [replaceable]#my-project#
[prompt]#$# [command]#ng# build
[prompt]#$# [command]#ng# test
[prompt]#$# [command]#ng# serve
----

[[vaadin-angular2-polymer.ng2cli.dependencies]]
== Adding Polymer Elements Dependencies

Polymer uses the http://bower.io/[Bower] package manager. Hence, you first  have to install and initialize Bower before continuing:

[subs="normal"]
----
[prompt]#$# [command]#npm# install bower -g
[prompt]#$# [command]#bower# init
----

By default, Bower installs dependencies in the [filename]#bower_components# folder. But Angular-CLI expects static stuff to be in the [filename]#public# directory. Thus, create the [filename]#.bowerrc# file in the root directory, with the following content:

[source,json]
.&#46;bowerrc
----
{
  "directory" : "public/bower_components"
}
----

Now, you can install all the Polymer elements that you need in your application.

For instance, to install all the elements in the https://elements.polymer-project.org/browse?package=paper-elements[Polymer Paper] collection, and the [elementname]#https://vaadin.com/elements/-/element/vaadin-combo-box[vaadin-combo-box]# element, run the following:

[subs="normal"]
----
[prompt]#$# [command]#bower# install --save [replaceable]#paper-elements vaadin-combo-box#
----

Next, we will create the [filename]#src/elements.html# file, where we put all the the links to the elements used by the application:

[source,html]
.src/elements.html
----
<link rel="import" href="bower_components/polymer/polymer.html">
<link rel="import" href="bower_components/paper-styles/color.html">
<link rel="import" href="bower_components/paper-styles/typography.html">
<link rel="import" href="bower_components/vaadin-combo-box/vaadin-combo-box.html">
<link rel="import" href="bower_components/paper-input/paper-input.html">
----

And finally, we modify our [filename]#src/index.html# file to load the web components polyfill and the new created file, and to wait for the [eventname]#WebComponentsReady# event before bootstrapping the application. Replace your [elementname]#body# with the following content:

[source,html]
.src/index.html
----
<body>
  <app-root>Loading...</app-root>
  {{#each scripts.polyfills}}<script src="{{.}}"></script>{{/each}}

  <script src="bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
  <link rel="import" href="elements.html">

  <script>
    document.addEventListener('WebComponentsReady', function() {
      System.import('system-config.js').then(function () {
        System.import('main');
      }).catch(console.error.bind(console));
    });
  </script>
</body>
----

Now you can run `ng serve`, open the application in your browser, and everything should work with no errors in the console.

[TIP]
The [filename]#webcomponents.js# polyfill is not necessary for browsers that fully implement the Web Components Spec like Chrome.

[NOTE]
Although we can add polymer dependencies to the [filename]#index.html# file, we do prefer to maintain the auxiliary [filename]#elements.html# file, so as we can reuse them in tests as is described below.

[[vaadin-angular2-polymer.ng2cli.directive]]
== Adding The Polymer Elements Directive

For using Polymer elements in the Angular 2 application, we need to import the [classname]#PolymerElement# directive from https://github.com/vaadin/angular2-polymer[@vaadin/angular2-polymer]. Thus we need to install the dependency by typing:

[subs="normal"]
----
[prompt]#$# [command]#npm# install --save @vaadin/angular2-polymer
----

Then, make the module loader aware of how to load the package by modifying the [filename]#src/system-config.ts# config as follows:

[source,typescript]
.src/system-config.ts
----
const map: any = {
  '@vaadin': 'vendor/@vaadin'
};
const packages: any = {
  '@vaadin/angular2-polymer': { main: 'index.js', defaultExtension: 'js' }
};
...
----

And make the `ng` builder include the directive package by modifying the [propertyname]#vendorNpmFiles# property in the [filename]#angular-cli-build.js# file.

[source,javascript]
.angular-cli-build.js
----
vendorNpmFiles: [
  ...
  '@vaadin/**/*.+(js|js.map)'
]
----


[[vaadin-angular2-polymer.ng2cli.using]]
== Using Polymer Elements

Now that everything is set, we can add any polymer elements to our application using their element names in templates, and the [classname]#PolymerElement# directive in code.
For example, modify the [filename]#src/app/app.component.html# to have the following code:

[source,html]
.src/app/app.component.html
----
<h3>{{title}}</h3>
<vaadin-combo-box [label]="myLabel" [(value)]="myValue" [items]="myItems"></vaadin-combo-box>
<paper-input [(value)]="myValue"></paper-input>
----

In the [filename]#src/app/app.component.ts# file, define the properties bound in the template and specify the initial values:

[source,typescript]
.src/app/app.component.ts
----
import { Component } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css']
})
export class AppComponent {
  title = 'app works!';
  myLabel = 'Select a number'
  myValue = '4';
  myItems = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
}
----

Then import and add the [classname]#PolymerElement# directives and the [classname]#CUSTOM_ELEMENTS_SCHEMA# to the [classname]#AppModule#. Open the [filename]#src/app/app.module.ts# file and replace the contents with the following code:

[source,typescript]
.src/app/app.module.ts
----
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { PolymerElement } from '@vaadin/angular2-polymer';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent,
    PolymerElement('vaadin-combo-box'),
    PolymerElement('paper-input')
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppModule { }
----
Finally, you can use Polymer custom CSS properties and custom CSS mixins either: in the [filename]#app.component.ts# file for the scoped styles, or in the [filename]#index.html# file for the global ones.
In the following example we use mixins and properties defined in the Paper [elementname]#color# and [elementname]#typography# elements.

[source,html]
.src/index.html
----
<head>
  ...
  <style is="custom-style">
    body {
      @apply(--paper-font-body1);
    }
  </style>
</head>
----

[source,css]
.src/app/app.component.css
----
paper-input,
vaadin-combo-box {
  background: var(--paper-grey-200);
  padding: 8px;
}
----

[[vaadin-angular2-polymer.ng2cli.testing]]
== Testing Polymer Elements

Angular-CLI projects come with https://karma-runner.github.io[Karma] tests.

Karma needs to be configured appropriately to import all needed Polymer elements, before running any test.

This is done in the [propertyname]#files# section of the [filename]#config/karma.conf.js# file as follows:

[source,javascript]
.config/karma.conf.js
----
    files: [
      ...
      'dist/bower_components/webcomponentsjs/webcomponents-lite.js',
      'dist/elements.html'
    ]
----
