---
title: Using in Angular CLI Webpack
order: 3
layout: page
---

:linkattrs:
[[vaadin-angular2-polymer.ng2cli]]
= Using Polymer Elements in Angular CLI Webpack Applications

[[vaadin-angular2-polymer.ng2cliwebpack.introduction]]
== Introduction

https://github.com/angular/angular-cli[Angular CLI] is a command line tool for Angular 2. It is not only a scaffolding tool for creating and modifying a project, but also for other actions like building, running, debugging, and testing the project.

In this document we will describe all the modifications you have to make to your Angular CLI project to use Polymer elements.

[[vaadin-angular2-polymer.ng2cliwebpack.preparation]]
== Preparation

We assume that you already have installed in your system the Angular CLI package and the `ng` command
is available in your PATH. Otherwise run the following command:

[subs="normal"]
----
[prompt]#$# [command]#npm# install -g @angular/cli
----

Then, create a new Angular 2 project.

[subs="normal"]
----
[prompt]#$# [command]#ng# new [replaceable]#my-project#
----

Check that everything works by compiling, testing, and running your new project:

[subs="normal"]
----
[prompt]#$# [command]#cd# [replaceable]#my-project#
[prompt]#$# [command]#ng# build
[prompt]#$# [command]#ng# test
[prompt]#$# [command]#ng# serve
----

When the development server is running you can test the application at http://localhost:4200[http://localhost:4200, role="external", window="_blank"].
Press kbd:[Ctrl+C] to stop the server.

[[vaadin-angular2-polymer.ng2cliwebpack.dependencies]]
== Adding Polymer Elements Dependencies

Polymer uses the http://bower.io/[Bower] package manager. Hence, you first  have to install and initialize Bower before continuing:

[subs="normal"]
----
[prompt]#$# [command]#npm# install bower -g
[prompt]#$# [command]#bower# init
----

By default, Bower installs dependencies to the [filename]#bower_components# folder. But Angular CLI expects static stuff to be in the [filename]#src/assets# directory.
Thus, create the [filename]#.bowerrc# file in the root directory, with the following content:

[source,json]
.&#46;bowerrc
----
{
  "directory" : "src/assets/bower_components"
}
----

Now, you can install all the Polymer elements that you need in your application.

For instance, to install all the elements in the https://elements.polymer-project.org/browse?package=paper-elements[Polymer Paper] collection,
and the [elementname]#https://vaadin.com/elements/-/element/vaadin-combo-box[vaadin-combo-box]# element, run the following:

[subs="normal"]
----
[prompt]#$# [command]#bower# install --save [replaceable]#paper-elements vaadin-combo-box#
----

[TIP]
====
Add the following line to the [filename]#.gitignore# file to prevent the Bower dependencies from being tracked by Git in future:

[source]
----
src/assets/bower_components
----
====

Next we will modify the application index HTML file to load the web components polyfill, and to import the Polymer elements.
Open the [filename]#src/index.html# file and append the following lines to the [elementname]#head# section:

[source,html]
.src/index.html head additions
----
<head>
  ...

  <script src="assets/bower_components/webcomponentsjs/webcomponents.min.js"></script>
  <script>
    window.Polymer = {
      dom: 'shadow'
    };
  </script>
  <link rel="import" href="assets/bower_components/paper-styles/color.html">
  <link rel="import" href="assets/bower_components/paper-styles/typography.html">
  <link rel="import" href="assets/bower_components/vaadin-combo-box/vaadin-combo-box.html">
  <link rel="import" href="assets/bower_components/paper-input/paper-input.html">
</head>
----

In Angular CLI Webpack projects, the main application file is automatically bundled and appended to the end of the [elementname]#body# section of the [filename]#index.html# file.
It means that the Angular application is imported and bootstrapped synchronously.
Meanwhile, Polymer elements are loaded from HTML Imports processed asynchronously in browsers that do not have a native support.

We have to wait for the Polymer elements to be loaded and registered before running the application code.
Therefore, we have to postpone the Angular application import until the [eventname]#WebComponentsReady# event is dispatched.
Create a new file [filename]#src/main-polymer.ts# with the following loader script:

[source,typescript]
.src/main-polymer.ts
----
document.addEventListener('WebComponentsReady', () => {
  require('./main.ts');
});
----

Change the main entry point of the application to load the new loader script.
Edit the [filename]#angular-cli.json# file in the project root and replace the line `"main": "main.ts",` with  `"main": "main-polymer.ts",`.

////
// TODO: `$ ng set` could be used for editing the config, but it is broken nowadays.
Replace the editing instructions above with the following paragraph after this PR is merged: https://github.com/angular/angular-cli/pull/1800

Run the following command to set the new [filename]#src/main-polymer.ts# file as the application entry point:

[subs="normal"]
----
[prompt]#$# [command]#ng# set apps.0.main main-polymer.ts
----
////

Now you can run `ng serve`, open the application in your browser, and everything should work with no errors in the console.

[TIP]
The [filename]#webcomponents.js# polyfill is not necessary for browsers that fully implement the Web Components Spec like Chrome.

[TIP]
====
Optionally, you can move the [filename]#webcomponents.min.js# from the application [filename]#index.html# to the [filename]#angular-cli.json# configuration file.

[source, json]
.angular-cli.json
----
{
  "scripts":[
    "assets/bower_components/webcomponentsjs/webcomponents.min.js"
  ]
}
----
====

[[vaadin-angular2-polymer.ng2cliwebpack.directive]]
== Adding The PolymerElement Package

For using Polymer elements in the Angular 2 application, we need to import the [classname]#PolymerElement#
directive from https://github.com/vaadin/angular2-polymer[@vaadin/angular2-polymer]. Thus we need to install the dependency by typing:

[subs="normal"]
----
[prompt]#$# [command]#npm# install --save @vaadin/angular2-polymer
----


[[vaadin-angular2-polymer.ng2cliwebpack.using]]
== Using Polymer Elements

Now that everything is set, we can add any Polymer elements to our application using their element names in templates,
and the [classname]#PolymerElement# directive in code.
For example, modify the [filename]#src/app/app.component.html# to have the following code:

[source,html]
.src/app/app.component.html
----
<h1>{{title}}</h1>
<vaadin-combo-box [label]="myLabel" [(value)]="myValue" [items]="myItems"></vaadin-combo-box>
<paper-input [(value)]="myValue"></paper-input>
----

In the [filename]#src/app/app.component.ts# file, define the properties bound in the template and specify the initial values:

[source,typescript]
.src/app/app.component.ts
----
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
})
export class AppComponent {
  title = 'app works!';
  myLabel = 'Select a number';
  myValue = '4';
  myItems = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
}
----

Then import and add the [classname]#PolymerElement# directives and the [classname]#CUSTOM_ELEMENTS_SCHEMA# to the [classname]#AppModule#.
Open the [filename]#src/app/app.module.ts# file and replace the contents with the following code:

[source,typescript]
.src/app/app.module.ts
----
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { PolymerElement } from '@vaadin/angular2-polymer';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent,
    PolymerElement('vaadin-combo-box'),
    PolymerElement('paper-input')
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [],
  entryComponents: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class AppModule { }
----

Finally, you can use Polymer custom CSS properties and custom CSS mixins in the [filename]#app.component.css#
file for the scoped styles, and in the [filename]#index.html# file for the global ones.
In the following example we use mixins and properties defined in the Paper [elementname]#color# and [elementname]#typography# elements.

[source,html]
.src/index.html
----
<head>
  ...
  <style is="custom-style">
    body {
      @apply(--paper-font-body1);
    }
  </style>
</head>
----

[source,css]
.src/app/app.component.css
----
paper-input,
vaadin-combo-box {
  background: var(--paper-grey-200);
  padding: 8px;
}
----

[[vaadin-angular2-polymer.ng2cliwebpack.testing]]
== Testing

Angular CLI projects come with https://karma-runner.github.io[Karma] tests.

Since tests are run against the testing module defined in the [filename]#app.component.spec.ts#, instead of
the one defined in the [filename]#app.module.ts#, you need to import the [classname]#CUSTOM_ELEMENTS_SCHEMA#
in the test file.

[source,typescript]
.src/app/app.component.spec.ts
----
import { CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
...

describe('App: NgApp', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent,
      ],
      schemas: [CUSTOM_ELEMENTS_SCHEMA]
    });
  });
  ...
});
----

Then, you can test elements API as usual. For example:

[source,typescript]
.src/app/app.component.spec.ts
----
...

it('vaadin-combo-box and paper-input should have an initial value of 4', async(() => {
  let fixture = TestBed.createComponent(AppComponent);
  fixture.detectChanges();
  let compiled = fixture.debugElement.nativeElement;
  let combobox = compiled.querySelector('vaadin-combo-box');
  let input = compiled.querySelector('paper-input');
  expect(combobox.value).toEqual('4');
  expect(input.value).toEqual('4');
}));
----
