[[vaadin-angular2-polymer.tutorial.creating-project]]
== Creating Project

This tutorial is based on the Angular 2 QuickStart TypeScript source code. In this step, we create a new project on top of the QuickStart source code.

[NOTE]
====
If you are not yet familiar with Angular 2, please go through the https://angular.io/docs/ts/latest/quickstart.html[Angular 2 QuickStart] tutorial, which explains every step of starting a new Angular 2 application from scratch.
====

=== Starting from the QuickStart Repository

Clone the https://github.com/angular/quickstart[QuickStart repository] into the tutorial project folder:

[subs="normal"]
----
[prompt]#$# [command]#git# clone https://github.com/angular/quickstart my-project
[prompt]#$# [command]#cd# my-project
----

We are not going to contribute to the quickstart repository itself, so the original repository data is not needed. Remove the git repository data folder:

[subs="normal"]
----
[prompt]#$# [command]#rm# -rf .git
----

=== Starting from the QuickStart ZIP Package

Alternatively, instead of using git to clone the QuickStart repository, you can download and extract the https://github.com/angular/quickstart/archive/master.zip[QuickStart zip package].

=== Remove the AppComponent Tests

The QuickStart respository contains tests for [classname]#AppComponent#. Unfortunately, some changes to [classname]#AppComponent# in the following steps are going to break the compilation for these tests.

Please remove the [filename]#app/app.component.spec.ts# file to prevent its compilation errors introduced later in this tutorial.

[NOTE]
.Testing in Angular 2
====
Testing is out of the scope of this tutorial.

See the https://angular.io/docs/ts/latest/guide/testing.html[Testing chapter] in the Angular 2 Developer Guide for more information on the topic.
====

=== Installing Npm Packages and Starting the Development Server

Install npm dependencies:

[subs="normal"]
----
[prompt]#$# [command]#npm# install
----

At this point you should be able to compile TypeScript source code and launch the development server. Let’s start the server to verify:

[subs="normal"]
----
[prompt]#$# [command]#npm# start
----

Press kbd:[Ctrl+C] to stop the development server.

[TIP]
====
See the https://github.com/angular/quickstart/blob/master/README.md[QuickStart README] for more information about creating a new project and other useful [command]#npm# commands.
====

