[[vaadin-angular2-polymer.tutorial.dependencies]]
== Adding and Installing Dependencies

After the previous step, we have an empty Angular 2 application source with all the Angular dependencies installed. In this step, we are going to add the Polymer library and some elements as dependencies of our application, and install them.

Vaadin Elements and other Polymer elements are mainly distributed through http://bower.io/[Bower]. We are going to use Bower to declare these dependencies and install them.

=== Adding Bower Dependencies

[IMPORTANT]
====
You should install Bower before we start using it. Use [command]#npm# to install Bower with this command:

[subs="normal"]
----
[prompt]#$# [command]#npm# install -g bower
----
====

Create [filename]#bower.json# file in your project root with the following contents:

[source,json]
.bower.json
----
{
  "name": "my-project",
  "description": "",
  "main": "",
  "authors": [
    "Your Name"
  ],
  "license": "ISC",
  "homepage": "",
  "private": true,
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test"
  ],
  "dependencies": {
    "polymer": "Polymer/polymer#^1.4.0",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#^1.3.1",
    "iron-icons": "PolymerElements/iron-icons#^1.1.3",
    "app-layout": "PolymerElements/app-layout#^0.9.0",
    "paper-styles": "PolymerElements/paper-styles#^1.1.4",
    "paper-icon-button": "PolymerElements/paper-icon-button#^1.1.1",
    "paper-input": "PolymerElements/paper-input#^1.1.11",
    "vaadin-grid": "Vaadin/vaadin-grid#^1.1.0",
    "vaadin-date-picker": "Vaadin/vaadin-date-picker#^1.1.0"
  }
}
----

This file declares all Bower dependencies for our application. Now install them with this command:

[subs="normal"]
----
[prompt]#$# [command]#bower# install
----

After that, in your project root you should have the [filename]#bower_components# directory with all elements declared in the [filename]#bower.json#, together with the elements’ requirements. List the contents of the [filename]#bower_components# directory to verify that, it should contain these subdirectories:

.Contents of the bower_components Directory
----
app-layout
font-roboto
iron-a11y-announcer
iron-a11y-keys-behavior
iron-autogrow-textarea
iron-behaviors
iron-checked-element-behavior
iron-dropdown
iron-fit-behavior
iron-flex-layout
iron-form-element-behavior
iron-icon
iron-icons
iron-iconset-svg
iron-input
iron-media-query
iron-meta
iron-overlay-behavior
iron-resizable-behavior
iron-scroll-target-behavior
iron-selector
iron-validatable-behavior
neon-animation
paper-behaviors
paper-button
paper-icon-button
paper-input
paper-material
paper-ripple
paper-styles
polymer
vaadin-date-picker
vaadin-grid
web-animations-js
webcomponentsjs
----

[TIP]
.Add bower_components to .gitignore
====
It is ususally a good practice to exclude external dependencies from your source control. Angular 2 QuickStart source code already contains a [filename]#.gitignore# file, which excludes [filename]#node_modules# directory with npm dependencies from git repository of your application.

Please add the following line to the [filename]#.gitignore# file to also prevent Bower dependencies from being tracked by your source control:

[source]
----
bower_components
----
====

=== Npm Dependency

Alongside with Bower dependencies, we also need to add one npm dependency to the project. `@vaadin/angular2-polymer` package adds support for Polymer elements in Angular 2 component templates. Run this command to install the package and save the dependency in [filename]#package.json# at the same time:

[subs="normal"]
----
[prompt]#$# [command]#npm# install @vaadin/angular2-polymer --save
----

